### DISCUSSION TITLE
posts/mkyarnmodules/

### DISCUSSION THREAD

**Discussion by giscus** [ajaxbits/ajaxbits-site#7] [Blog Comments]
# posts/mkyarnmodules/

https://ajaxbits.com/posts/mkyarnmodules/

**Comment by siddarthkay** [comment]
Thanks I too use yarn2nix and came here looking for a bun alternative.
`bun install --yarn` was nice advice.

Thank you.

**Comment by pietdevries94** [comment]
Thanks for the writeup!
For people just wanting to make sure their yarn.lock is always in sync with bun.lockb, add this to bunfig.toml:
```toml
[install.lockfile]
# whether to save a non-Bun lockfile alongside bun.lockb
# only "yarn" is supported
print = "yarn"
```

https://bun.sh/docs/runtime/bunfig#install-lockfile
